### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by Wirone** [Mapudo/guzzle-bundle#28]
Currently in `composer.json` max Symfony version supported by bundle is `4.*`. Please provide compatibility for Symfony 5.

FYI: we use fork with `|~5.0` added and it works, so probably it's all that needs to be done.

**Comment by kobelobster** [comment]
Hey @Wirone - Could you also check https://github.com/Mapudo/guzzle-bundle/pull/29

Sadly, mapudo is no more and we're all working on other projects (I'm not even developing in PHP anymore) so I don't have the tools anymore on my pc to check. :(

**Comment by Wirone** [comment]
@kobelobster #29 is created by my colleague because we needed it in project (upgrade to Symfony 5), so we can continue there :slightly_smiling_face:

**Comment by Wirone** [comment]
Don't need it anymore and since I don't want it on "my issues" list, I'm going to close it now.

**Comment by kobelobster** [comment]
@Wirone Hey. Sorry, the company that worked on this has dissolved and I switched to ASP.NET Core a few years ago, so I'm not working/maintaining this lib anymore
